# Generated by Django 3.2.9 on 2021-11-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_tearleadsuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
