# Generated by Django 5.1.7 on 2025-03-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_backfill_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
