---
allowBuilds:
  '@ffmpeg-installer/darwin-arm64': true
  '@ffmpeg-installer/darwin-x64': true
  '@ffmpeg-installer/linux-arm': true
  '@ffmpeg-installer/linux-arm64': true
  '@ffmpeg-installer/linux-ia32': true
  '@ffmpeg-installer/linux-x64': true
  '@ffmpeg-installer/win32-ia32': true
  '@ffmpeg-installer/win32-x64': true
  '@swc/core': false
  edgedriver: true
  esbuild: true
  geckodriver: true
  msw: false
overrides:
  '@babel/plugin-transform-modules-systemjs@<=7.29.3': 7.29.4
  '@puppeteer/browsers@^2.2.0': 3.2.0
  '@xmldom/xmldom@<0.8.13': 0.8.13
  'rollup@<4.59.0': 4.62.4
  'serialize-javascript@<7.0.5': 7.1.0
  'tmp@<0.2.7': 0.2.7
  'uuid@<11.1.1': 11.1.1
  'webpack@<5.104.1': 5.104.1
