repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/PyCQA/isort
    # should match what is inside of requirements/local.txt
    rev: 6.1.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    # should match what is inside of requirements/local.txt
    rev: 25.9.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    # should match what is inside of requirements/local.txt
    rev: 7.1.1
    hooks:
    -   id: flake8
