repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/PyCQA/isort
    # should match what is inside of requirements/local.txt
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    # should match what is inside of requirements/local.txt
    rev: 24.4.2
    hooks:
    -   id: black
