---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        files: ^scripts/.*\.sh$
  - repo: local
    hooks:
      - id: check-for-unpinned-dependencies
        name: check-for-unpinned-dependencies
        entry: npx check-for-unpinned-dependencies
        pass_filenames: false
        language: node
      - id: biome-check-fix
        name: biome check --write
        entry: npx biome check --write
        pass_filenames: false
        language: node
      - id: tsc -b
        name: tsc -b
        entry: pnpm tsc -b
        pass_filenames: false
        language: system
      - id: yamllint
        name: yamllint
        entry: yamllint .
        pass_filenames: false
        language: system
