version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
  conf:
  vhost:
  html:
  dhparam:
  certs:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - certs:/etc/nginx/certs:ro
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=${LETSENCRYPT_EMAIL}

  backend:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - .:/app:cached
    ports:
      - "9001:9001"
    links:
      - postgres
    environment:
      - VIRTUAL_HOST=${API_FQDN}
      - LETSENCRYPT_HOST=${API_FQDN}
      - LETSENCRYPT_TEST=true

  frontend:
    image: tearleads-frontend
    env_file: .env
    environment:
      - VIRTUAL_HOST=${WEB_FQDN}
      - LETSENCRYPT_HOST=${WEB_FQDN}
      - LETSENCRYPT_TEST=true

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    env_file: .env