# Generated by Django 3.0.2 on 2020-12-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0006_auto_20200723_0236"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="entry_count",
            field=models.IntegerField(default=0),
        ),
    ]
