# Generated by Django 3.0.2 on 2020-12-14 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0009_tag_date_last_used"),
    ]

    def forwards_func(apps, schema_editor):
        Tag = apps.get_model("tags", "Tag")
        for tag in Tag.objects.all():
            most_recent_tag_to_text_entry = (
                tag.tag_to_text_entry.all().order_by("-date_created").first()
            )
            if most_recent_tag_to_text_entry is None:
                tag.date_last_used = None
            else:
                tag.date_last_used = most_recent_tag_to_text_entry.date_created
            tag.save(update_fields=["date_last_used"])

    operations = [
        migrations.RunPython(forwards_func),
    ]
