# Generated by Django 3.1.13 on 2021-08-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0012_auto_20210706_1211"),
    ]

    def forwards_func(apps, schema_editor):
        Tag = apps.get_model("tags", "Tag")
        for tag in Tag.objects.all():
            tag.date_last_used = tag.date_created
            tag.save(update_fields=["date_last_used"])

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
