# Generated by Django 3.1.13 on 2021-10-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0013_backfill_date_last_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
