repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.108.1
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.11.0.1
  hooks:
    - id: shellcheck
- repo: https://github.com/ansible/ansible-lint
  rev: v26.8.0
  hooks:
    - id: ansible-lint
      additional_dependencies:
        - ansible-core==2.21.3
      always_run: false
      args:
        - ansible
      files: ^ansible/.*\.ya?ml$
- repo: local
  hooks:
    - id: commitlint
      name: Commitlint
      entry: npx --no-install commitlint --edit
      language: system
      stages:
        - commit-msg
