# Generated by Django 3.0.2 on 2020-03-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("text_entries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textentry",
            options={"ordering": ["date_updated", "id"]},
        ),
    ]
