# Generated by Django 3.0.2 on 2020-06-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_entries", "0002_auto_20200321_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textentry",
            name="body",
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="textentry",
            name="subject",
            field=models.CharField(max_length=255),
        ),
    ]
