# Generated by Django 3.0.2 on 2020-12-08 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("text_entries", "0005_textentry_tag_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="textentry",
            name="reused_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="textentry",
            name="reused_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name="TextEntryReused",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "text_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_entry_resuses",
                        to="text_entries.TextEntry",
                    ),
                ),
            ],
            options={
                "ordering": ["date_created", "id"],
            },
        ),
    ]
