- name: ssh configuration
  copy:
    src: ./configs/ssh
    dest: "/home/{{ ansible_user }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0400'

- name: Clone backend repository
  git:
    repo: github-backend.com:tearleads/tearleads-backend.git
    dest: "/home/{{ ansible_user }}/tearleads-backend"
    accept_hostkey: yes
    force: no
    recursive: no
    version: "{{ git_branch }}"
