---
- name: Get server's SSH RSA public key
  shell: cat /etc/ssh/ssh_host_rsa_key.pub
  register: server_ssh_key
  changed_when: false

- name: Display server's SSH RSA public key
  debug:
    var: server_ssh_key.stdout
