- name: create .aws directory
  file:
    path: ~/.aws
    state: directory
    mode: '0700'

- name: configure aws credentials
  copy:
    dest: ~/.aws/credentials
    mode: '0600'
    content: |
      [default]
      aws_access_key_id = {{ ecr_access_key_id }}
      aws_secret_access_key = {{ ecr_secret_access_key }}

- name: configure aws region
  copy:
    dest: ~/.aws/config
    mode: '0600'
    content: |
      [default]
      region = us-east-1
