---
- name: Create the .aws directory
  ansible.builtin.file:
    path: ~/.aws
    state: directory
    mode: "0700"

- name: Configure AWS credentials
  ansible.builtin.copy:
    dest: ~/.aws/credentials
    mode: "0600"
    content: |
      [default]
      aws_access_key_id = {{ lookup('ansible.builtin.env', 'ECR_ACCESS_KEY_ID') }}
      aws_secret_access_key = {{ lookup('ansible.builtin.env', 'ECR_SECRET_ACCESS_KEY') }}
  no_log: true

- name: Configure the AWS region
  ansible.builtin.copy:
    dest: ~/.aws/config
    mode: "0600"
    content: |
      [default]
      region = us-east-1
