---
- name: Copy .env file to remote host
  ansible.builtin.copy:
    src: >-
      {{ lookup('ansible.builtin.env',
      'ANSIBLE_' ~ (env_name | upper) ~ '_ENV_FILE') }}
    dest: "/home/{{ ansible_user }}/commandsnippets/backend/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0600"
