- name: tearleads-backend deploy key
  copy:
    src: ../ssh_keys/tearleads-backend-deploy-key
    dest: "/home/{{ ansible_user }}/.ssh/tearleads-backend-deploy-key"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0400'

- name: tearleads-frontend deploy key
  copy:
    src: ../ssh_keys/tearleads-frontend-deploy-key
    dest: "/home/{{ ansible_user }}/.ssh/tearleads-frontend-deploy-key"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0400'
