- name: install docker
  package:
    name: docker.io
    state: present
    force_apt_get: True
    update_cache: yes

- name: install docker-compose
  package:
    name: docker-compose
    state: present
    force_apt_get: True
    update_cache: yes

- name: Add the application service account to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker

- name: Create the network
  community.docker.docker_network:
    name: tearleads
