- name: Schedule containers startup on boot
  cron:
    name: "start containers on boot"
    special_time: reboot
    job: "cd /home/{{ ansible_user }}/tearleads-backend/ && docker compose -f container-registry.yaml up -d >/home/{{ ansible_user }}/docker-startup-log 2>&1"
    user: "{{ ansible_user }}"
  register: cron_result
