# Generated by Django 3.0.2 on 2020-03-31 13:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200327_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtextentrythroughmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagtextentrythroughmodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
