# Generated by Django 3.0.2 on 2020-12-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0007_tag_entry_count"),
    ]

    def forwards_func(apps, schema_editor):
        Tag = apps.get_model("tags", "Tag")
        for tag in Tag.objects.all():
            entry_count = tag.text_entries.count()
            tag.entry_count = entry_count
            tag.save(update_fields=["entry_count"])

    operations = [
        migrations.RunPython(forwards_func),
    ]
