# Generated by Django 3.0.2 on 2020-12-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0008_backfill_entry_count_on_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="date_last_used",
            field=models.DateTimeField(null=True),
        ),
    ]
