# Generated by Django 3.1.4 on 2021-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0011_tag_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=24),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("name", "user_id"), name="One tag of same name per user"
            ),
        ),
    ]
