# Generated by Django 3.2.9 on 2021-11-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_tearleadsuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TearleadsUser",
        ),
    ]
