- hosts: staging
  become: yes
  become_user: root
  tasks:
    - include_tasks: tasks/install-aws-cli.yaml
    - include_tasks: tasks/install-docker.yaml
   #- include_tasks: tasks/install-microk8s.yaml
    - include_tasks: tasks/authorized_keys.yaml

- hosts: staging
  tasks:
    - include_tasks: tasks/copy-deploy-keys.yaml
    - include_tasks: tasks/clone-repos.yaml
    - include_tasks: tasks/schedule-api-backup.yaml
    - include_tasks: tasks/start-api-on-boot.yaml
    - include_tasks: tasks/patch-and-reboot-daily.yaml

- hosts: production
  become: yes
  become_user: root
  tasks:
    - include_tasks: tasks/install-aws-cli.yaml
    - include_tasks: tasks/install-docker.yaml
    - include_tasks: tasks/authorized_keys.yaml
    - include_tasks: tasks/start-api-on-boot.yaml
    - include_tasks: tasks/patch-and-reboot-daily.yaml

- hosts: production
  tasks:
    - include_tasks: tasks/copy-deploy-keys.yaml
    - include_tasks: tasks/clone-repos.yaml
    - include_tasks: tasks/schedule-api-backup.yaml
