- hosts: staging
  become: yes
  become_user: root
  tasks:
    - include: tasks/install-packages-ubuntu-20.yaml
    - include: tasks/configure-users.yaml
    
- hosts: staging
  tasks:
    - include: tasks/copy-deploy-keys.yaml
    - include: tasks/clone-repos.yaml
    - include: tasks/schedule-api-backup.yaml
    - include: tasks/authorized_keys.yaml

- hosts: production
  become: yes
  become_user: root
  tasks:
    - include: tasks/install-packages-ubuntu-20.yaml
    - include: tasks/configure-users.yaml
    - include: tasks/authorized_keys.yaml
      
- hosts: production
  tasks:
    - include: tasks/copy-deploy-keys.yaml
    - include: tasks/clone-repos.yaml
    - include: tasks/schedule-api-backup.yaml
  