- hosts: staging
  become: yes
  become_user: root
  tasks:
    - include: tasks/install-packages-ubuntu-20.yaml
    
- hosts: staging
  tasks:
    - include: tasks/clone-repos.yaml
    - include: tasks/copy-deploy-keys.yaml