# Generated by Django 3.0.2 on 2020-07-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_entries", "0003_auto_20200628_0441"),
    ]

    operations = [
        migrations.AddField(
            model_name="textentry",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
