# Generated by Django 3.0.2 on 2020-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_entries", "0004_textentry_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="textentry",
            name="tag_count",
            field=models.IntegerField(default=0),
        ),
    ]
