# Generated by Django 3.0.2 on 2020-12-08 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("text_entries", "0006_auto_20201208_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="textentryreused",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_entry_resuses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
