name: Github Actions
on:
  push:
    branches: '**'
  schedule:
    - cron: '0 0 * * *'
jobs:
  code-quality:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: npm ci
        run: npm ci
      - name: pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
      - run: npx vitest --no-watch
      - run: npm run ci-headless
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: wdio-video-reporter
          path: |
            _results_
            package.json
      - name: Post to slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  deploy-code:
    runs-on: ubuntu-latest
    continue-on-error: false
    needs: code-quality
    steps:
      - uses: actions/checkout@v4
      # production deploy
      - uses: amondnet/vercel-action@v25
        name: production deploy
        if: ${{ github.event.ref == 'refs/heads/production' && github.event_name == 'push' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      # staging deploy
      - uses: amondnet/vercel-action@v25
        name: non-production deploy
        if: ${{ github.event.ref == 'refs/heads/staging' && github.event_name == 'push' }}
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: Post to slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
